/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tiktaktoee;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
/**
 *
 * @author JUAN
 */
public class Bot extends javax.swing.JFrame {

   int turno;
   int empate =0;
   Random rnd = new Random();
    public Bot() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicio = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        btn5 = new javax.swing.JTextField();
        btn6 = new javax.swing.JTextField();
        btn8 = new javax.swing.JTextField();
        btn9 = new javax.swing.JTextField();
        btn7 = new javax.swing.JTextField();
        btn1 = new javax.swing.JTextField();
        btn2 = new javax.swing.JTextField();
        btn3 = new javax.swing.JTextField();
        btn4 = new javax.swing.JTextField();
        lblGanador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInicio.setText("INICIO");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });

        btnReiniciar.setText("Reiniciar");
        btnReiniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReiniciarMouseClicked(evt);
            }
        });

        btn5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn5KeyTyped(evt);
            }
        });

        btn6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn6KeyTyped(evt);
            }
        });

        btn8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn8KeyTyped(evt);
            }
        });

        btn9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn9KeyTyped(evt);
            }
        });

        btn7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn7KeyTyped(evt);
            }
        });

        btn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn1KeyTyped(evt);
            }
        });

        btn2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn2KeyTyped(evt);
            }
        });

        btn3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn3KeyTyped(evt);
            }
        });

        btn4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                btn4KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lblGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(6, 6, 6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnInicio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 130, Short.MAX_VALUE)))
                    .addGap(6, 6, 6)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(306, Short.MAX_VALUE)
                .addComponent(lblGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInicio)
                        .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(33, 33, 33)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(90, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void turno(JTextField control) {
        if (turno == 0) {
            control.setText("X");
            control.setEnabled(false);
            turno = 1;
           
            if (turno == 1) {
                 int numRND = rnd.nextInt(8) + 1;
                if (numRND == 1 ) {
                    if (btn1.getText().length() == 0) {
                        btn1.setText("O");
                        btn1.setEnabled(false);
                        turno = 0;
                    } else{
                        numRND = rnd.nextInt(8) + 1;
                    }
                }
                else if (numRND == 2) {
                    if (btn2.getText().length() == 0) {
                        btn2.setText("O");
                        btn2.setEnabled(false);
                        turno = 0;
                    } else{
                        numRND = rnd.nextInt(8) + 1;
                    }
                }
               else if (numRND == 3) {
                    if (btn3.getText().length() == 0) {
                        btn3.setText("O");
                        btn3.setEnabled(false);
                        turno = 0;
                    } else{
                       numRND = rnd.nextInt(8) + 1; 
                    }
                }
               else if (numRND == 4) {
                    if (btn4.getText().length() == 0) {
                        btn4.setText("O");
                        btn4.setEnabled(false);
                        turno = 0;
                    } else{
                        numRND = rnd.nextInt(8) + 1;
                    }
                }
               else if (numRND == 5) {
                    if (btn5.getText().length() == 0) {
                        btn5.setText("O");
                        btn5.setEnabled(false);
                        turno = 0;
                    } else
                        numRND = rnd.nextInt(8) + 1;
                }
               else if (numRND == 6) {
                    if (btn6.getText().length() == 0) {
                        btn6.setText("O");
                        btn6.setEnabled(false);
                        turno = 0;
                    } else
                        numRND = rnd.nextInt(8) + 1;
                }
               else if (numRND == 7) {
                    if (btn7.getText().length() == 0) {
                        btn7.setText("O");
                        btn7.setEnabled(false);
                        turno = 0;
                    } else
                        numRND = rnd.nextInt(8) + 1;
                }
               else if (numRND == 8) {
                    if (btn8.getText().length() == 0) {
                        btn8.setText("O");
                        btn8.setEnabled(false);
                        turno = 0;
                    } else
                        numRND = rnd.nextInt(8) + 1;
                }
              else  if (numRND == 9) {
                    if (btn9.getText().length() == 0) {
                        btn9.setText("O");
                        btn8.setEnabled(false);
                        turno = 0;
                    } else{
                        
                    }
                        
                    
                }

            } // TURNO
        }
    }

    public void ganador() {
        lblGanador.setText("Ganador Jugador " + btn1.getText());
        getContentPane().setBackground(new Color(0, 255, 0));
    }

    public void validacion() {
        if (btn1.getText().equals(btn2.getText()) && btn2.getText().equals(btn3.getText()) && !btn1.getText().isEmpty()) {
            ganador();
        } else if (btn1.getText().equals(btn4.getText()) && btn4.getText().equals(btn7.getText()) && !btn1.getText().isEmpty()) {
            ganador();
        } else if (btn1.getText().equals(btn5.getText()) && btn5.getText().equals(btn9.getText()) && !btn1.getText().isEmpty()) {
            ganador();
        } else if (btn2.getText().equals(btn5.getText()) && btn5.getText().equals(btn8.getText()) && !btn2.getText().isEmpty()) {
            ganador();
        } else if (btn4.getText().equals(btn5.getText()) && btn5.getText().equals(btn6.getText()) && !btn4.getText().isEmpty()) {
            ganador();
        } else if (btn7.getText().equals(btn8.getText()) && btn8.getText().equals(btn9.getText()) && !btn7.getText().isEmpty()) {
            ganador();
        } else if (btn3.getText().equals(btn6.getText()) && btn6.getText().equals(btn9.getText()) && !btn3.getText().isEmpty()) {
            ganador();
        } else if (btn3.getText().equals(btn5.getText()) && btn5.getText().equals(btn7.getText()) && !btn3.getText().isEmpty()) {
            ganador();
        } else {
            empate++;
            if(empate == 9){
                lblGanador.setText("EMPATE");
            }
        }
    }
    
    
    
    
    
    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        Principal a = new Principal();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnReiniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReiniciarMouseClicked
        if (lblGanador.getText().contains("Ganador Jugador") || lblGanador.getText().contains("EMPATE")) {
            btn1.setText("");
            btn2.setText("");
            btn3.setText("");
            btn4.setText("");
            btn5.setText("");
            btn6.setText("");
            btn7.setText("");
            btn8.setText("");
            btn9.setText("");
            btn1.setEnabled(true);
            btn2.setEnabled(true);
            btn3.setEnabled(true);
            btn4.setEnabled(true);
            btn5.setEnabled(true);
            btn6.setEnabled(true);
            btn7.setEnabled(true);
            btn8.setEnabled(true);
            btn9.setEnabled(true);
            turno = 0;
            getContentPane().setBackground(new Color(240, 240, 240));
            lblGanador.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Eres un cobarde por abandonar la partida");
        }
    }//GEN-LAST:event_btnReiniciarMouseClicked

    private void btn5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn5KeyTyped
        turno(btn5);
        validacion();
    }//GEN-LAST:event_btn5KeyTyped

    private void btn6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn6KeyTyped
        turno(btn6);
        validacion();
    }//GEN-LAST:event_btn6KeyTyped

    private void btn8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn8KeyTyped
        turno(btn8);
        validacion();
    }//GEN-LAST:event_btn8KeyTyped

    private void btn9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn9KeyTyped
        turno(btn9);
        validacion();
    }//GEN-LAST:event_btn9KeyTyped

    private void btn7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn7KeyTyped
        turno(btn7);
        validacion();
    }//GEN-LAST:event_btn7KeyTyped

    private void btn1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn1KeyTyped
        turno(btn1);
        validacion();
    }//GEN-LAST:event_btn1KeyTyped

    private void btn2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn2KeyTyped
        turno(btn2);
        validacion();
    }//GEN-LAST:event_btn2KeyTyped

    private void btn3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn3KeyTyped
        turno(btn3);
        validacion();
    }//GEN-LAST:event_btn3KeyTyped

    private void btn4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn4KeyTyped
        turno(btn4);
        validacion();
    }//GEN-LAST:event_btn4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bot().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btn1;
    private javax.swing.JTextField btn2;
    private javax.swing.JTextField btn3;
    private javax.swing.JTextField btn4;
    private javax.swing.JTextField btn5;
    private javax.swing.JTextField btn6;
    private javax.swing.JTextField btn7;
    private javax.swing.JTextField btn8;
    private javax.swing.JTextField btn9;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel lblGanador;
    // End of variables declaration//GEN-END:variables
}
